--- #YAML:1.0
name:               Bundle-Biodiverse
version:            0.15
abstract:           Bundle for Biodiverse dependencies
author:
    - Shawn Laffan (shawn.laffan@unsw.edu.au)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Browser::Open:        0
    Data::DumpXML:        0
    ExtUtils::Depends:    0
    ExtUtils::PkgConfig:  0
    Geo::ShapeFile:       0
    Gtk2::GladeXML:       0
    LWP::Simple:          0
    Tree::R:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
