---
abstract: 'Bundle for Biodiverse dependencies'
author:
  - 'Shawn Laffan (shawn.laffan@unsw.edu.au)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-Biodiverse
no_index:
  directory:
    - t
    - inc
requires:
  Browser::Open: 0
  Data::DumpXML: 0
  Geo::ShapeFile: 0
  Gtk2::GladeXML: 0
  Tree::R: 0
version: 0.16
